### ISSUE TITLE
Oprogramowanie graficzne - makieta

### ISSUE THREAD

**Issue by KevinCwiek** [TheGamesAmongUs/Start#11]
Zapoznaj się z oprogramowaniem Pencil, i przygotuj makietę. Plik zauploaduj na dysk Google do folderu "Pliki" i w repozytorium "Dokumenty" powiadom o tym przez dodanie pliku "Makieta" zawierającym samą informację. Po zapoznaniu się z makietą odpowiem w tym samym pliku i będziesz mógł zaczynać pracę nad całą grafiką.

Czas realizacji (całości): do 31.03.2015

**Comment by RichForever** [comment]
Makieta została wykonana oraz zamieszczona na dysku google drive w katalogu TheGamesAmongUs/Pliki/Pliki graficzne
