### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by KevinCwiek** [TheGamesAmongUs/Start#4]
Zaprojektuj faviconkę strony, oraz przygotuj też wersję większą, którą wykorzystamy, jako logo projektu w tym serwisie.

Czas realizacji: do 15.03.2015

**Comment by M92PL** [comment]
Logo oraz favicona zostały wykonane. Pliki zostały umieszczone na dysku google w katalogu TheGamesAmongUs/Pliki/Pliki graficzne.

**Comment by RichForever** [comment]
Logo oraz favicona zostały wykonane. Pliki zostały umieszczone na dysku google w katalogu TheGamesAmongUs/Pliki/Pliki graficzne.
