### ISSUE TITLE
Mapa konceptualna

### ISSUE THREAD

**Issue by KevinCwiek** [TheGamesAmongUs/Start#6]
Zrób mapę konceptualną. Może być narysowana na kartce, lub bezpośrednio w UML'u. Zauploaduj bezpośrednio na dysk Google w "Pliki" i napisz w "Dokumentach" na GitHubie, że mapa znajduje się na dyski i w jakiej wersji.

Czas na realizację: do 15.03.2015

PS ostatnio bardzo ładnie wychodziło ci przenoszenie rzeczy, do UML'a więc chciałbym abyś i tym razem się tym zajął. Więc te pliki, które będą na dysku google w formacie np zdjęcia - to chciałbym, abyś się nimi zajął.

**Comment by mazur160** [comment]
Mapa konceptualna już znajduje się na google drive w dokumentach.
